export const POST_ENDPOINT = 'https://jsonplaceholder.typicode.com/posts';

//posts list
export const FILTER_POSTS = 'FILTER_POSTS';
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

//posts detail
export const FETCH_POST_DETAIL = 'FETCH_POST_DETAIL';
export const FETCH_POST_DETAIL_SUCCESS = 'FETCH_POST_DETAIL_SUCCESS';
export const FETCH_POST_DETAIL_FAILURE = 'FETCH_POST_DETAIL_FAILURE';

//authentication
export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE';
export const AUTHENTICATE_VALIDATION_FAILURE = 'AUTHENTICATE_VALIDATION_FAILURE';
export const AUTHENTICATE_LOCAL_STORAGE_KEY = 'AUTHENTICATE_LOCAL_STORAGE_KEY_TEST_APP';
export const AUTHENTICATE_LOGOUT_SUCCESS = 'AUTHENTICATE_LOGOUT_SUCCESS';
